spring:
  data:
    mongodb:
       uri: mongodb+srv://mongo:mongo2020@mongoflex-fyxlp.mongodb.net/mongoflex?retryWrites=true
      #uri: mongodb+srv://mongo:mongo2020@cluster0-5hqnc.mongodb.net/cluster0?retryWrites=true&w=majority
   
